on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: node build dist
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm i
    - run: npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: www44.your-server.de
        username: redsla
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        local-dir: ./dist/
        server-dir: ./
